// Fill out your copyright notice in the Description page of Project Settings.


#include "GameProgressBarUI.h"

#include "PlayerMarkerWidget.h"
#include "Components/BoxComponent.h"
#include "Components/Overlay.h"
#include "Components/ProgressBar.h"
#include "GameFramework/PlayerState.h"
#include "JumpGame/Core/GameInstance/JumpGameInstance.h"
#include "JumpGame/Core/GameState/MapGameState.h"
#include "JumpGame/Props/LogicProp/GameFinishProp.h"
#include "JumpGame/Props/LogicProp/GameStartProp.h"
#include "JumpGame/Props/LogicProp/RisingWaterProp.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "Net/UnrealNetwork.h"

void UGameProgressBarUI::NativeOnInitialized()
{
	Super::NativeOnInitialized();
	
	// í”„ë¡œê·¸ë ˆìŠ¤ ë°”ì—ì„œ í‘œì‹œí•  ë§ˆì»¤ ìœ„ì¹˜ê°’
	AGameStartProp* StartProp = Cast<AGameStartProp>(UGameplayStatics::GetActorOfClass(GetWorld(), AGameStartProp::StaticClass()));
	ARisingWaterProp* WaterProp = Cast<ARisingWaterProp>(UGameplayStatics::GetActorOfClass(GetWorld(), ARisingWaterProp::StaticClass()));

	StartPropZ = StartProp->GetActorLocation().Z;
	WaterPropZ = WaterProp->SurfaceCollision->GetComponentLocation().Z;

	GI = Cast<UJumpGameInstance>(GetWorld()->GetGameInstance());
	
	// ëª¨ë“  í”Œë ˆì´ì–´ë“¤ì˜ ê°’ì´ ì—…ë°ì´íŠ¸ ë˜ì—ˆë‹¤ë©´ ì´ í•¨ìˆ˜ë¥¼ ì‹¤í–‰í•´ì•¼í•¨
	AMapGameState* GS = Cast<AMapGameState>(GetWorld()->GetGameState());
	GS->OnAllClientAddedDelegate.AddDynamic(this, &UGameProgressBarUI::InitUISetting);
	
}

void UGameProgressBarUI::NativeTick(const FGeometry& MyGeometry, float DeltaSeconds)
{
	Super::NativeTick(MyGeometry, DeltaSeconds);

	AGameFinishProp* FinishProp = Cast<AGameFinishProp>(UGameplayStatics::GetActorOfClass(GetWorld(), AGameFinishProp::StaticClass()));
	if (!FinishProp) return;
	FinPropZ = FinishProp->GetActorLocation().Z;
	if (bIsInit)
	{
		// ì§€ì†ì ìœ¼ë¡œ ì—…ë°ì´íŠ¸ í•˜ì
		UpdateProgressBar();
	}
}

void UGameProgressBarUI::InitUISetting()
{
	FFastLogger::LogScreen(FColor::Red, TEXT("InitUISetting!!!!!!"));
	
	CreatePlayerMarkers();
	bIsInit = true;
}

void UGameProgressBarUI::UpdatePlayerPos()
{
	AMapGameState* GS = Cast<AMapGameState>(GetWorld()->GetGameState());
	if (!GS) return;
	
	PlayerPos.SetNum(GS->PlayerArray.Num());
	
	// ê·¸ ì¤‘ 1ë“± í”Œë ˆì´ì–´ì˜ ìœ„ì¹˜
	WinnerPos = 0.f;

	int32 PlayerIndex = 0;
	for (APlayerState* PlayerState : GS->PlayerArray)
	{
		// AController* Controller = PlayerState->GetOwner<AController>();
		AFrog* Frog = Cast<AFrog>(PlayerState->GetPawn());
		if (Frog)
		{
			if (PlayerPos.IsValidIndex(PlayerIndex))
			{
				// FFastLogger::LogConsole(TEXT("UpdatePlayerPos: %d"),PlayerIndex);
				// í”Œë ˆì´ì–´ ìœ„ì¹˜ê°’(Zì¢Œí‘œì„) ì €ì¥
				float CurrentPosition = Frog->GetActorLocation().Z - 30.f;
				
				PlayerPos[PlayerIndex] = CurrentPosition; // PlayerIDì— í•´ë‹¹í•˜ëŠ” ì¸ë±ìŠ¤ì— ì €ì¥
				// 1ë“± í”Œë ˆì´ì–´ ìœ„ì¹˜ ê°±ì‹ 
				WinnerPos = FMath::Max(WinnerPos, CurrentPosition);
			}
		}
		PlayerIndex++;
	}
}

void UGameProgressBarUI::UpdateProgressBar()
{
	// í”Œë ˆì´ì–´ ì •ë³´ ì—…ë°ì´íŠ¸ë°›ê³  (1ë“± í¬í•¨)
	UpdatePlayerPos();
	
	// 1ë“± í”Œë ˆì´ì–´ ê¸°ì¤€ìœ¼ë¡œ í”„ë¡œê·¸ë ˆìŠ¤ ë°” ì—…ë°ì´íŠ¸ ì‹œí‚¤ì
	float CurrentWinnerPos = WinnerPos - StartPropZ;
	TotalGamePos = FinPropZ - StartPropZ;
	GameProgressBar->SetPercent(CurrentWinnerPos / TotalGamePos);

	// ë§ˆì»¤ ìœ„ì¹˜ë„ ì—…ë°ì´íŠ¸í•˜ì
	UpdatePlayerMarkers();
}

void UGameProgressBarUI::CreatePlayerMarkers()
{
	// ê¸°ì¡´ ë§ˆì»¤ ì œê±°
	for (UPlayerMarkerWidget* ExistingMarker : PlayerMarkers)
	{
		if (ExistingMarker)
		{
			ExistingMarker->RemoveFromParent();
		}
	}
	PlayerMarkers.Empty();

	AMapGameState* GS = Cast<AMapGameState>(GetWorld()->GetGameState());
	if (!GS) return;
	
	PlayerMarkers.SetNum(GS->PlayerArray.Num());
	FFastLogger::LogConsole(TEXT("GS->PlayerArray.Num(): %d"), GS->PlayerArray.Num());
	
	int32 PlayerIndex = 0;
	for (APlayerState* PlayerState : GS->PlayerArray)
	{
		// AController* Controller = PlayerState->GetOwner<AController>();
		AFrog* Frog = Cast<AFrog>(PlayerState->GetPawn());
		
		if (Frog)
		{
			// ë§ˆì»¤ ìœ„ì ¯ ìƒì„±
			UPlayerMarkerWidget* NewMarker = CreateWidget<UPlayerMarkerWidget>(GetWorld(), PlayerMarkerFactory);
			if (NewMarker)
			{
				FFastLogger::LogConsole(TEXT("CreatePlayerMarkers: %d"),PlayerIndex);
				// ìœ„ì ¯ì„ í”„ë¡œê·¸ë ˆìŠ¤ ë°” ì»¨í…Œì´ë„ˆì— ì¶”ê°€
				Overlay_Player->AddChild(NewMarker);
				// í”Œë ˆì´ì–´ IDì™€ ì •ë³´ ì„¤ì •
				NewMarker->SetPlayerID(PlayerIndex);
        
				// ìœ„ì ¯ ì´ˆê¸° ìœ„ì¹˜ ì„¤ì •
				FVector2D TopLeft = Overlay_Player->GetCachedGeometry().GetAbsolutePosition(); // ì¢Œì¸¡ ìƒë‹¨
				FVector2D Size = Overlay_Player->GetCachedGeometry().GetLocalSize(); // ìœ„ì ¯ í¬ê¸°
				FVector2D BottomRight = TopLeft + FVector2D(Size.X, Size.Y); // ìš°ì¸¡ í•˜ë‹¨
		
				NewMarker->SetRenderTranslation(BottomRight);
        
				// ë¡œì»¬ í”Œë ˆì´ì–´ í™•ì¸í•˜ì—¬ ìƒ‰ìƒ ì„¤ì •
				if (Frog->IsLocallyControlled())
				{
					NewMarker->SetColorAndOpacity(FColor::Green);
				}
				else
				{
					NewMarker->SetColorAndOpacity(FColor::Yellow);
				}
        
				// PlayerID ì¸ë±ìŠ¤ì— ë§ˆì»¤ ì €ì¥
				PlayerMarkers[PlayerIndex] = NewMarker;
				FFastLogger::LogConsole(TEXT("PlayerIndex: %d"), PlayerIndex);

				PlayerIndex++;
			}
		}
	}
}

void UGameProgressBarUI::UpdatePlayerMarkers()
{
	// ProgressBar í¬ê¸° ê¸°ì¤€ìœ¼ë¡œ ìœ„ì¹˜ ê²°ì •
	float BarHeight = GameProgressBar->GetCachedGeometry().GetLocalSize().Y;
	
	// ëª¨ë“  í”Œë ˆì´ì–´ ë§ˆì»¤ ìœ„ì¹˜ ì—…ë°ì´íŠ¸
	for (int32 i = 0; i < PlayerMarkers.Num(); i++)
	{
		UPlayerMarkerWidget* Marker = PlayerMarkers[i];
		if (!Marker || !PlayerPos.IsValidIndex(i)) continue;
        
		// ì§„í–‰ë„ ê³„ì‚°
		float PlayerProgress = (PlayerPos[i] - StartPropZ) / TotalGamePos;
		PlayerProgress = FMath::Clamp(PlayerProgress, 0.0f, 1.0f);
		
		float MarkerY = BarHeight * (1.0f - PlayerProgress) - 30.f; // ì´ë¯¸ì§€ í¬ê¸° (30)
		FVector2D MarkerPos(0.f, MarkerY);
		
		// ë§ˆì»¤ ìœ„ì¹˜ ì„¤ì •
		Marker->SetRenderTranslation(MarkerPos);

		// ğŸŸ¢ í›„ì²˜ë¦¬ ì—°ì¶œ ì¶”ê°€
		AMapGameState* GS = Cast<AMapGameState>(GetWorld()->GetGameState());
		if (!GS || !GS->PlayerArray.IsValidIndex(i)) continue;

		AFrog* Frog = Cast<AFrog>(GS->PlayerArray[i]->GetPawn());
		if (Frog && Frog->IsLocallyControlled())
		{
			float FogValue = FMath::Lerp(0.f, 1.f, PlayerProgress * 1.5f); // í•„ìš”ì‹œ ì»¤ë¸Œ ì ìš©

			Frog->SetFrogVignetteIntensity_PP(1.f - FogValue);
			Frog->SetLightIntensity(FogValue);
			UpdateFogDensity(FogValue);
			UpdateSunBrightness(FogValue);

			UE_LOG(LogTemp, Warning, TEXT("FogValue: %f"), FogValue);
		}
	}
}
